#!/usr/bin/python3

def raise_exception_msg(message=""):
    '''
    Raise a NameError exception with custom msg

    Args:
        message: Custom msg passed as argument to the exception
    '''
    raise NameError(message)
